Commission:
  stage: build
  rules:
    - when: manual
  script:
    - ssh root@$MAAS-Server "bash commission.sh"
Deploy-machines:
  stage: deploy
  script:
    - ssh root@$MAAS-Server "bash network-bond.sh ; bash deploy-partition.sh"
